### ISSUE TITLE
just a default ember addon?

### ISSUE THREAD

**Issue by 100ideas** [ef4/cardstack-editor#1]
Have you published any cardstack source code to this repo or is it just auto-generated by ember-cli? Can't tell.

**Comment by ef4** [comment]
[Yes there is source code](https://github.com/ef4/cardstack-cms/commits/master).

**Comment by 100ideas** [comment]
Cool, I'm looking forward to learning more about the design patterns for data exchange you work out... I'll keep an eye on https://github.com/ef4/cardstack-cms/tree/master/app/controllers & https://github.com/ef4/cardstack-cms/tree/master/app/serializers.
